# Generated by Django 5.2.1 on 2025-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description', models.CharField(max_length=500, verbose_name='Описание курса')),
                ('course_topics', models.CharField(max_length=500, verbose_name='Темы курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Изображение урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('text', models.TextField(verbose_name='Информация урока')),
                ('video', models.TextField(verbose_name='Видео урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
